x_offset: 0.005
y_offset: 0.02
z_offset: 0.04
roll_offset: -1.999999984507266
pitch_offset: -6.000000166965211
yaw_offset: 3.000000083482606
hip_pitch_offset: 7.000000052497138
period_time: 600
dsp_ratio: 0.25
step_forward_back_ratio: 0.05
foot_height: 0.03
swing_right_left: 0
swing_top_down: 0
pelvis_offset: 0
arm_swing_gain: 0
balance_hip_roll_gain: 0.5
balance_knee_gain: 0.75
balance_ankle_roll_gain: 0.6
balance_ankle_pitch_gain: 0.6
p_gain: 0
i_gain: 0
d_gain: 0